
using System;
using Microsoft.CodeAnalysis;

namespace SourceGenerator
{
    [Generator]
    public class HelloWorldGenerator :ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            //Console.WriteLine("a");
        }

        public void Execute(GeneratorExecutionContext context)
        {
            var mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);
            var source =  $@"// <auto-generated/>
using System;

namespace {mainMethod.ContainingNamespace.ToDisplayString()}
{{
    public static partial class {mainMethod.ContainingType.Name}
    {{
        static partial void HelloFrom(string name) =>
            Console.WriteLine($""Generator says: Hi from \'{{name}}\'"");
    }}
}}
";
            var typeName = mainMethod?.ContainingType.Name ?? "Program";
            context.AddSource($"{typeName}.g.cs", source);
        }
    }
}